version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.0.0
  cli: circleci/circleci-cli@0.1.4

jobs:
  validate:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/validate:
          orb-path: src/@orb.yml

workflows:
  publish:
    jobs:
      - orb-tools/lint
      - validate
      - shellcheck/check:
          dir: ./src/scripts
          filters: *filters
      - orb-tools/publish-dev:
          context: circleci-orb
          orb-name: signavio/aws-ecr-eks
          orb-path: src/@orb.yml
          checkout: true
          publish-token-variable: CIRCLE_TOKEN
          requires:
            - orb-tools/lint
            - validate
            - shellcheck/check
      - orb-tools/dev-promote-prod-from-commit-subject:
          context: circleci-orb
          orb-name: signavio/aws-ecr-eks
          checkout: true
          add-pr-comment: true
          publish-token-variable: CIRCLE_TOKEN
          publish-version-tag: false
          fail-if-semver-not-indicated: false
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master
